[IT-1783, IT-1663] use node16 platform in dev
Sage-Bionetworks/agora2-infra pull request #3
Opened 2022-04-06 19:31 UTC by JessterB

2022-04-06 20:17 UTC, zaro0508 requested changes

2022-04-06 20:17 UTC, zaro0508 commented on config/develop/agora.yaml
> +  EbSolutionStackName: '64bit Amazon Linux 2 v5.5.0 running Node.js 16'
i think we want to make the change to all environments?  if you agree then please update `config/staging/agora.yaml` and `config/prod/agora.yaml` as well.

2022-04-07 16:21 UTC, JessterB commented on config/develop/agora.yaml
> +  EbSolutionStackName: '64bit Amazon Linux 2 v5.5.0 running Node.js 16'
I've updated the other environments.

2022-04-07 16:29 UTC, zaro0508 approved these changes

2022-04-15 21:13 UTC, merged